spring:
  application:
    name: tvmaze-api
  config:
    import: optional:file:.env[.properties]
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/tvmaze}
  data:
    mongodb:
      auto-index-creation: true
  http:
    clients:
      connect-timeout: 3s
      read-timeout: 5s

server:
  port: 8080

tvmaze:
  base-url: https://api.tvmaze.com

